###
#

cluster.name: "docker-cluster"
network.host: 0.0.0.0

### https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html
# bootstrap.memory_lock: true
xpack.monitoring.enabled: true
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
# xpack.monitoring.ui.container.elasticsearch.enabled: true
