version: '3.2'
services:
######################################
###################################### DOCKER-UI
######################################
  portainer:
    # build: ./portainer
    image: portainer
    # privileged: true
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://portainer:9000/"]
      retries: 5
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: volume
        source: portainer
        target: /data
    ports:
      - "9000:9000"
    #depends_on:
    #  - nginx
    networks:
      - localnet

volumes:
    portainer:
      driver: local

