apm-server:
  host: 0.0.0.0:8200
  frontend.enabled: true
  frontend.allow_origins: "*"
#    path: /kibana
  ### Real User Monitoring
#  rum:
#    enabled: true

max_procs: 4
queue.mem.events: 4096
logging.to_files: false
logging.level: INFO
logging.selectors: [ "beat", "service" ]

setup.kibana.host: "kibana:5601"

# monitoring.enabled: true

# X-Pack
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
  hosts: [ "elasticsearch:9200" ]
  username: "elastic"
  password: "changeme"

output:
  logstash:
    hosts: [ "logstash:5044" ]

#output:
#  elasticsearch:
#    hosts: ['elasticsearch:9200']
#    protocol "http"
#    username: elastic
#    password: changeme





