apm-server:
  host: 0.0.0.0:8200
#    path: /kibana
  ### Real User Monitoring
#  rum:
#    enabled: true

max_procs: 4
queue.mem.events: 4096
logging.level: info
setup.kibana.host: "kibana:5601"

logging.to_files: false

# xpack.monitoring.enabled: false
# xpack.monitoring.elasticsearch:
# monitoring.enabled: true
# monitoring.elasticsearch: true

output:
  logstash:
    hosts: ["http://logstash:5044"]

#output:
#  elasticsearch:
#    hosts: ['http://elasticsearch:9200']
#    protocol "http"
#    username: elastic
#    password: changeme





