ARG ELK_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

### RUN elasticsearch-plugin install analysis-icu
#RUN elasticsearch-plugin -install mobz/elasticsearch-head

#USER root
#ENV TZ=Europe/Kiev
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#USER elasticsearch

