# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: main
  pipeline.workers: 5
  pipeline.batch.size: 25
  pipeline.ordered: auto
  path.config: "/usr/share/logstash/pipeline/main.conf"

- pipeline.id: beats
  pipeline.workers: 3
  pipeline.batch.size: 5
  pipeline.ordered: auto
  path.config: "/usr/share/logstash/pipeline/beats.conf"

- pipeline.id: nginx
  pipeline.workers: 1
  pipeline.batch.size: 5
  pipeline.ordered: auto
  path.config: "/usr/share/logstash/pipeline/nginx.conf"

